
[general]
import = [
"current_theme.toml"
]


[font]
# ls ~/.local/share/fonts
# fc-list : familiy | sort -f | grep Nerd
normal = { family = "JetBrainsMono NFM", style = "Regular" }
bold = { family = "JetBrainsMono NFM", style = "Bold" }
italic = { family = "JetBrainsMono NFM", style = "Italic" }
bold_italic = { family = "JetBrainsMono NFM", style = "BoldItalic" }
size = 14


[window]
opacity=1
startup_mode = "Maximized"
# macOS only option
option_as_alt = "Both"
# option_as_alt = "OnlyLeft"


[[hints.enabled]]
# enable OSC 8 escape sequence hyperlinks. example: 
# $printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'

#command = "xdg-open" # On Linux/BSD
command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }


# Detect plain URLs (www.google.com, https://..., ftp://...)
[[hints.enabled]]
regex = "(https?|ftp|file)://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]"
command = "open" # On macOS
mouse.enabled = true

# [[hints.enabled]]
# regex = '\bwww\.[-A-Za-z0-9]+\.[-A-Za-z0-9]+(\.[-A-Za-z0-9]+)*\b'
# command = "open" # On macOS
# mouse.enabled = true


# [[hints.enabled]]
# regex = "[^ ]+\\.rs:\\d+:\\d+"
# command = { program = "code", args = [ "--goto" ] }
# mouse = { enabled = true }


[mouse]
bindings = [
    { mouse = "Left", mods = "Control", action="Open" },
]

[keyboard]
bindings = [
    { key = "g", mods = "Super", chars="gitui\n" },
    { key = "e", mods = "Super", chars="fg\n" },
# override default behavior of alacritty
    { key = "b", mods = "Control | Shift", action="None" },
# actions
    { key = "=", mods = "Control", action="IncreaseFontSize" },
    { key = "-", mods = "Control", action="DecreaseFontSize" },
    { key = "0", mods = "Control", action="ResetFontSize" },
# new window
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" }
    ## { key = "i", mods = "Control | Shift", action="ToggleViMode" },
# not working
#{ key = "t", mods = "Super", action="CreateNewTab" },
]

